on:
  schedule:
    - cron: '*/12 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: Apchibudzdravij/tf_test_db@main
        with:
          url: https://tf-extension-assistant.onrender.com
