on:
  schedule:
    - cron: '*/12 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: Tyrrrz/action-http-request@1.1.2
        with:
          url: https://tf-extension-assistant.onrender.com
